name: Remote SSH Command

on:
  push:
    branches:
      - master  # Trigger the action on push to the main branch

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: enji.bamuel.com
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}  # Use SSH key for authentication
          port: 22  # Replace with the correct SSH port if it's not the default (22)
          script: |
            cd ${{ secrets.DEPLOY_PATH }}  # Use the DEPLOY_PATH secret for the project directory
            git fetch origin  # Fetch the latest changes from the remote repository
            git reset --hard origin/master  # Reset local changes and make local branch match the remote
            composer install --no-dev --optimize-autoloader  # Use --no-dev in production
            git pull origin master  # Pull the latest changes from the remote repository
